export const GATE_PASSWORD_KEYBOARD_TYPE = 'GATE_PASSWORD_KEYBOARD_TYPE'
export const GATE_PASSWORD_KEYBOARD_ERASE = 'GATE_PASSWORD_KEYBOARD_ERASE'
export const ALARM_CONFIGURATION_SUBMIT = 'ALARM_CONFIGURATION_SUBMIT'
